### ISSUE TITLE
mySQL credentials in error message

### ISSUE THREAD

**Issue by lmvco** [kaltura/kmc-login#1]
I am doing tests to a self hosted KMC instance (version 5).

For some reason, the mySQL deamon has shut down so the login failed (as expected). The problem is that the mySQL credentials were included in error message (see screenshot below).

![kmc_login](https://cloud.githubusercontent.com/assets/1884391/3599660/2e12ff04-0cf1-11e4-9537-22dde1f13850.png)

For security reasons, the mySQL credentials must not be included in this error message. I suggest to use a more generic error message.

**Comment by jessp01** [comment]
Hello,

Sorry for the delay in response.. this issue has been resolved a long time ago [version 6, we are now at 10].
It was actually an issue with the server side and not the KMC login widget.
In any event, thank you for reporting it and I hope you've since upgraded:)
