### ISSUE TITLE
after install  nonSSL login admin user to SSL addr

### ISSUE THREAD

**Issue by turbiko** [kaltura/kmc-login#2]
fresh install centOS 6.6 minimal 
I am create second admin user
when try to loginn in  Kaltura Management Console (KMC)
send me from login screen at 
http://mediana.film.ua/kmc
to
 https://mediana/index.php/kmc/kmc4
but installed as no SSL
installed by instructions at 
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
for centos 6.6
----------answer files
# ls

anaconda-ks.cfg  install.log.syslog       kaltura_04_02_11_04.ans
install.log      kaltura_04_02_11_01.ans
# cat kaltura_04_02_11_01.ans

TIME_ZONE="Europe/Kiev"
KALTURA_FULL_VIRTUAL_HOST_NAME="mediana:80"
KALTURA_VIRTUAL_HOST_NAME="mediana"
DB1_HOST="127.0.0.1"
DB1_PORT="3306"
DB1_PASS="Jz$qL6y51yBtQ11I74"
DB1_NAME="kaltura"
DB1_USER="kaltura"
SERVICE_URL="mediana"
SPHINX_SERVER1="127.0.0.1"
SPHINX_SERVER2=" "
DWH_HOST="127.0.0.1"
DWH_PORT="3306"
SPHINX_DB_HOST="127.0.0.1"
SPHINX_DB_PORT="3306"
ADMIN_CONSOLE_ADMIN_MAIL="email@email.com"
ADMIN_CONSOLE_PASSWORD="password"
CDN_HOST="mediana"
KALTURA_VIRTUAL_HOST_PORT="80"
SUPER_USER="root"
SUPER_USER_PASSWD="sqlrootpass"
ENVIRONMENT_NAME="Kaltura Video Platform"
DWH_PASS="DDT#$%TG%#"
PROTOCOL="http"
RED5_HOST="mediana"
USER_CONSENT="1"
CONTACT_MAIL="email@email.com"
VOD_PACKAGER_HOST="mediana"
VOD_PACKAGER_PORT="88"
IP_RANGE="0.0.0.0-255.255.255.255"
[root@mediana ~]# cat kaltura_04_02_11_04.ans
CONFIG_CHOICE="0"
IS_SSL="N"

**Comment by jessp01** [comment]
Hi,

What is the output for:
use kaltura;
select \* from permission WHERE permission.NAME='FEATURE_KMC_ENFORCE_HTTPS'\G

If it returns something, try to delete that record.

**Comment by turbiko** [comment]
Get the following output:
Database changed
mysql> select \* from permission WHERE permission.NAME='FEATURE_KMC_ENFORCE_HTTPS                                                    '\G
**************************\* 1. row ***************************
                         id: 243
                       type: 2
                       name: FEATURE_KMC_ENFORCE_HTTPS
              friendly_name: Force KMC HTTPS
                description:
                 partner_id: 0
                     status: 1
depends_on_permission_names:
                       tags:
                 created_at: 2015-02-03 11:41:15
                 updated_at: 2015-02-03 11:41:15
                custom_data: a:1:{s:13:"partner_group";s:0:"";}
**************************\* 2. row ***************************
                         id: 307
                       type: 2
                       name: FEATURE_KMC_ENFORCE_HTTPS
              friendly_name: NULL
                description: NULL
                 partner_id: 101
                     status: 2
depends_on_permission_names: NULL
                       tags: NULL
                 created_at: 2015-02-03 14:22:12
                 updated_at: 2015-02-03 14:22:12
                custom_data: NULL
2 rows in set (0.06 sec)

**Comment by turbiko** [comment]
That is help me! THANK You
mysql> DELETE FROM permission  WHERE id=243;
Query OK, 1 row affected (0.00 sec)

mysql> DELETE FROM permission  WHERE id=307;
Query OK, 1 row affected (0.01 sec)

mysql> select \* from permission WHERE permission.NAME='FEATURE_KMC_ENFORCE_HTTPS'\G
Empty set (0.00 sec)

**Comment by jessp01** [comment]
Happy to help and closing the issue.
